language: python
python:
  - '3.7'
  - '3.8'
  - '3.8-dev'
  - 'nightly'
install:
  - pip install -r requirements.txt
  - snyk test
script:
  - pytest tests/
  - pylint wb/
  - snyk test
after_success:
  - snyk monitor
after_deploy:
  - snyk monitor
deploy:
  provider: heroku
  api_key:
    secure: 'YOUR ENCRYPTED API KEY'
  app: my-app-123
