dist: xenial
language: python
python:
  - '3.7'
  - '3.8'
  - '3.7-dev'
  - '3.8-dev'
install:
  - pip install -r requirements.txt
script:
  - pytest tests/
  - pylint wb/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
after_success:
  - snyk monitor
after_deploy:
  - snyk monitor
