language: python
python:
  - '3.8'
cache: pip
install:
  - npm i -g snyk
  - pip install coverage
  - pip install codecov
  - pip install -r requirements.txt
script:
  - snyk auth $SNYK_TOKEN
  - snyk test
  # - coverage report
  # - pytest tests/
  # - pylint wb/
after_success:
  - snyk monitor
  # - codecov
  # - codeclimate-test-reporter
deploy:
  provider: heroku
  app: workflow-builder-api
  api_key:
    secure: '$HEROKU_TOKEN'
